### ISSUE TITLE
Flag 10 Problem

### ISSUE THREAD

**Issue by brendabrandy** [hackgnar/ble_ctf#5]
When i got up to Flag 10, the flag is already there without me solving anything. Is that an intended event or a side effect of completing flags 1-9?

**Comment by decidedlygray** [comment]
That doesn't sound like how the game works.. Does your score increase to 10/20? I know it might wreck some of the fun, but it might be worth [looking at some of the previous flags](https://github.com/hackgnar/ble_ctf/blob/9c7d52b4c6811f6fd2b94376e9051cb80d8e4757/main/gatts_table_creat_demo.c#L870) to make sure you didn't solve a later challenge with an earlier flag. I only mention this because this happened to me.

**Comment by hackgnar** [comment]
If you spent a lot of time on 1-9, yes it might pop up.  Going to mark this as complete.  I don't want to go into a full explanation as it might give the challenge away =)
